development:
  endpoint: "http://www.google-analytics.com/collect"
  version: 1
  tracking_code: UA-40704539-3

production:
  endpoint: "http://www.google-analytics.com/collect"
  version: 1
  tracking_code: UA-40704539-2