arts_music:
  art: 'other-art'
  cooking: 'cooking'
  dance: 'dance'
  drama: 'drama'
  music: 'music'
  other: 'other-art'
camp: 'camp'
family: 'parents'
parents_activity:
  business_team: 'parents'
  committee: 'parents'
  neighborhood_group: 'parents'
  networking_group: 'parents'
  non_profit: 'parents'
  religious: 'parents'
  social: 'parents'
  sports: 'parents'
  other: 'parents'
playgroup: 'playgroup'
religious: 'religious'
school_related: 'school-pta'
scouts: 'scouts'
sports:
  baseball: 'baseball'
  basketball: 'basketball'
  football: 'football'
  golf: 'golf'
  gymnastics: 'gymnastics'
  gym: 'gym'
  karate: 'karate'
  lacrosse: 'lacrosse'
  running: 'running'
  soccer: 'soccer'
  swimming: 'swimming'
  tennis: 'tennis'
  other: 'other-sports'
volunteer: 'volunteer'
other: 'other'